// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-ihRQ7mSeOARjK5PahkzuE6HF58Hwzo',
    appId: '1:154753155568:web:8416f72f786c4df7965d35',
    messagingSenderId: '154753155568',
    projectId: 'flutter-blog-d92eb',
    authDomain: 'flutter-blog-d92eb.firebaseapp.com',
    storageBucket: 'flutter-blog-d92eb.appspot.com',
    measurementId: 'G-DYTK4S56KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3a3PlO_QHPb4rdRtBqBU-39Jh0ot1HoY',
    appId: '1:154753155568:android:4b1e4deae375029a965d35',
    messagingSenderId: '154753155568',
    projectId: 'flutter-blog-d92eb',
    storageBucket: 'flutter-blog-d92eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBriwEw8LSEZrmQdVI4J6KEsqlzkrD-UXk',
    appId: '1:154753155568:ios:773aea16cde09fcf965d35',
    messagingSenderId: '154753155568',
    projectId: 'flutter-blog-d92eb',
    storageBucket: 'flutter-blog-d92eb.appspot.com',
    iosClientId: '154753155568-eqduinnigbbk111gf99m4mrpq3hae79b.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
